### PR TITLE
Zh Translation

### PR DESCRIPTION
**Pull request by snie2012**
Somehow, the CSS style (for example: font color and rotation) for Chinese character is not working. Would you mind taking a look? @ncase  Thanks.

### CODE REVIEW

**Comment by chinchihyu** [comment]
hi @snie2012, I have done the proofreading.
I am using github desktio
When I update the zh.html, it showed this
image
how can I have the permission to modify the file?
I think it's better to have a different css file for better support (also similar font in    ###Chinese)

**Comment by snie2012** [comment]
@chinchihyu , can you send me a pull request? You should be able to do that.

**Comment by chinchihyu** [comment]
@fititnt thanks for your note! I did change the font-size to 22px!

I also add a Chinese font for similar visual style as the English one.
image

@snie2012 I sent the pull request (guess I sent to the right place this time?)

https://github.com/snie2012/remember/pull/1#issue-231760865

**Comment by fititnt** [comment]
@snie2012 @chinchihyu Ah, I think the next translators for languages that use non-latin alphabet possibly should consider this approach to manage both styles (add one additional CSS file, if have significant changes) and even take in consideration the need to include a different webfont instead of rely on Helvetica/Arial default.

I will remember that for other localization projects!

**Comment by ncase** [comment]
谢谢! Your translation is now live at: https://ncase.me/remember/zh.html

**Pull request merged**
