### PR TITLE
Catalan translation complete!

### LINKED ISSUE #19: Translation: CA - Catalan
Started working a translation to catalan here: https://github.com/saimonmoore/remember/tree/catalan_translation

Feel free to help out!

### PR DESCRIPTION
**Pull request by saimonmoore**
fixes #19 

Cool. Now I can send this off to my kids school and also get them to read it (They already read it in spanish but now I can force them to read it in catalan too ha ha).

Nicky this is awesome work. Here's a pic of the Leitner box my kids and I created out of an empty tissue box (We each made our own):

leitner-box

Thanks a lot for doing this. Big fan now.

### CODE REVIEW

**Comment by saimonmoore** [comment]
@ncase ping

**Comment by ncase** [comment]
Hi @saimonmoore ! Sorry I'm terrible at emails – I literally haven't checked my email in almost two weeks.

Thank you again so much for doing this translation!  And _especially_ thank you for the photo of your Leitner Box: I've been saving all these photos, because it's just so meaningful to see my interactives inspired others to make cool things of their own.

Many thanks again! 🎉   I pulled your PR, and will soon also add it to the `gh-pages` branch so it goes live :)

**Comment by saimonmoore** [comment]
Glad you liked the photo. Thanks for making this very cool thing.

**Comment by saimonmoore** [comment]
@ncase I don't see the catalan translation live yet. Did I do something wrong or is it just that you haven't gotten round to it yet?

**Comment by ncase** [comment]
Hi @saimonmoore! So sorry – I was busy analyzing the statistics from my latest project ( https://ncase.me/experiment-stats/ ) and trying to get the report online before the end of the month. Thank you for waiting, your translation is now live online!  https://ncase.me/remember/ca.html  Many, many thanks again!  🎉

**Comment by saimonmoore** [comment]
ooh nice thanks....Sorry to pester...

I'l to check out the stats project.

Cheers

El dl., 28 de gen. 2019 a les 16:40, Nicky Case (<notifications@github.com>)
va escriure:

**Comment by ncase** [comment]
No worries, thanks for reminding me!

**Comment by saimonmoore** [comment]
@ncase what's the best way to contact you directly (I see email doesn't work ;) ? 

I'd like to ask you about hints for digital lettering in web comics.

**Pull request merged**
